### ISSUE TITLE
Frontend tests initialize with vitest

### ISSUE THREAD

**Issue by treva556** [Mazingira-Bros/mazingira#7]

**Comment by JoseMwanzia** [comment]
- [ ] Landing Page: This component will display the organizations that users can donate to and provide options to create an account or login.
- [ ] Registration/Login Form: This component will allow users to register for a new account or login to their existing account.
- [ ] Organization List: This component will display the list of organizations that users can choose to donate to, with relevant information such as organization name, logo, and donation options.
- [ ] Donation Form: This component will allow users to select an organization, choose the donation amount, and set up automated repeat donations or one-time donations. It should also provide options for anonymous donations and reminders for monthly donations.
- [ ] Beneficiary Stories: This component will display stories of beneficiaries who have been helped by the donations, with relevant images and information.
- [ ] Donor Dashboard: This component will provide donors with a dashboard to view their donation history, set up and manage automated donations, and update their profile information.
- [ ] Organization Dashboard: This component will provide the approved organizations with a dashboard to view the donations received, manage beneficiary stories, and update their organization details.
- [ ] Administrator Dashboard: This component will provide the administrator with a dashboard to review and approve/reject organization applications, and manage organizations.
- [ ] Navigation Bar: This component will provide a navigation bar with links to different pages of the platform for easy navigation.
- [ ] Footer: This component will display relevant information such as contact details, social media links, and copyright information
- [ ] Modals/Dialogs: There might be need for modal or dialog components for displaying pop-up messages, confirmation dialogs, and other interactive elements.
